# Generated by Django 4.2.8 on 2023-12-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('investment_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('cashflow_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cashflow_date', models.DateField()),
                ('cashflow_currency', models.CharField(max_length=3)),
                ('cashflow_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='investment.loan')),
            ],
        ),
    ]
